export type StripeColor =
  | 'stripe-light-primary-a'
  | 'stripe-dark-primary-a'
  | 'stripe-tertiary-a'
  | 'stripe-secondary-b'
  | 'stripe-neutral'
  | 'stripe-light-blue'
  | 'stripe-dark-blue'
  | 'stripe-green'
  | 'stripe-yellow'
  | 'stripe-gray';

export type TitleVariant =
  | 'caption'
  | 'date'
  | 'display'
  | 'eyebrow'
  | 'eyebrow-with-background'
  | 'subtitle'
  | 'paragraph'
  | 'small'
  | 'medium'
  | 'heading-1'
  | 'heading-2'
  | 'heading-3'
  | 'heading-4'
  | 'heading-5'
  | 'heading-6'
  | 'hero-text'
  | 'side-heading'
  | 'card-heading'
  | 'highlight-eyebrow'
  | 'heading-block'
  | 'banner'
  | 'universal';
