/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonVariant } from "./components/lbj-button/lbj-button-types";
import { IconColor, IconName, Size, VerticalStripeColor } from "./utils/enums";
import { IconVariant } from "./components/lbj-icon/lbj-icon-types";
import { LinkState, LinkVariant } from "./components/lbj-link/lbj-link-types";
import { StripeColor, TitleVariant } from "./components/lbj-title/lbj-title-types";
export { ButtonVariant } from "./components/lbj-button/lbj-button-types";
export { IconColor, IconName, Size, VerticalStripeColor } from "./utils/enums";
export { IconVariant } from "./components/lbj-icon/lbj-icon-types";
export { LinkState, LinkVariant } from "./components/lbj-link/lbj-link-types";
export { StripeColor, TitleVariant } from "./components/lbj-title/lbj-title-types";
export namespace Components {
    /**
     * The primary button component.
     * @element lbj-button
     */
    interface LbjButton {
        /**
          * Defines active state of button
         */
        "activeState": boolean;
        /**
          * The button case ( optional ) by default is Uppercase
          * @default 'uppercase'
         */
        "case": 'none' | 'capitalize' | 'uppercase' | 'lowercase';
        /**
          * Width of button
         */
        "fullwidth": boolean;
        /**
          * If no url, then falls back to <button> element (optional).
         */
        "href": string;
        /**
          * An icon to display to the right of text (optional).
         */
        "icon": IconName | undefined;
        /**
          * An icon to display to the left of text (optional).
         */
        "iconleft": IconName | undefined;
        /**
          * An icon to display to the right of text (optional).
          * @default Size.FULL
         */
        "iconsize": Size;
        /**
          * Determines if the button is a breakout button.
          * @default false
         */
        "isBreakout": boolean;
        /**
          * Display mode when nested inside another component.
         */
        "mode": string;
        /**
          * Modifier class
         */
        "modifier": string;
        /**
          * Dropdown nav items.
          * @default []
         */
        "navItems": { title: string; url: string }[];
        /**
          * The internal padding size. sm|md|lg|xl|xxl
          * @default Size.MD
         */
        "size": Size;
        /**
          * Defines target for links (optional).
         */
        "target": string;
        /**
          * Defines title case of button
         */
        "titleCase": boolean;
        /**
          * The button styling to display.
          * @default ButtonVariants.BTN_PRIMARY
         */
        "variant": ButtonVariant;
    }
    /**
     * Design icons for lyndon.
     * @element lbj-icon
     */
    interface LbjIcon {
        /**
          * The icon color to display.
          * @default IconColor.CURRENT
         */
        "color": IconColor;
        "filetype": string;
        /**
          * The registered icon to display.
          * @default IconName.ARROW_RIGHT
         */
        "name": IconName;
        /**
          * An optional property to add height/width to an icon.
         */
        "size": Size;
        /**
          * The icon variant to display.
          * @default 'default'
         */
        "variant": IconVariant;
    }
    /**
     * A introductory lede component.
     * @element lbj-lede
     */
    interface LbjLede {
        /**
          * The text contents of the accent title.
         */
        "accent": string;
        /**
          * The Array contents of the Author.
          * @default []
         */
        "author": Array<{ name: string; url: string }>;
        /**
          * @default false
         */
        "blank_target": boolean;
        /**
          * The different variants of the Lede.
          * @default 'lede'
         */
        "componentvariant": string;
        /**
          * The text contents of the date.
         */
        "date": string;
        /**
          * The text contents of the eyebrow title and url.
         */
        "eyebrow"?: Array<{ name: string; url: string }> | string | null;
        /**
          * The file type indicator.
         */
        "filetype": string;
        /**
          * Evaluate if Author slot has content.
         */
        "hasAuthor": boolean;
        /**
          * Evaluate if summary slot has content.
         */
        "hasSummary": boolean;
        /**
          * Evaluate if Topic slot has content.
         */
        "hasTopic": boolean;
        /**
          * The text contents of the headline title.
         */
        "headline": string;
        /**
          * @default false
         */
        "headline_html": boolean;
        /**
          * A wrapping URL for the headline title.
         */
        "href": string;
        "icon": string;
        /**
          * The text contents of the summary.
         */
        "summary": string;
        /**
          * The tags to display below the headline.
          * @default []
         */
        "tags": Array<{ name: string; url: string }>;
        /**
          * The array contents of the primary topic/ second eyebrow.
          * @default []
         */
        "topic": Array<{ name: string; url: string }>;
    }
    /**
     * The primary link component.
     * @element lbj-link
     */
    interface LbjLink {
        /**
          * Dropdown position.
          * @default 'floating'
         */
        "dropdown"?: 'static' | 'floating';
        /**
          * Whether the link has children.
         */
        "hasChildren": boolean;
        /**
          * The URL that the hyperlink points to.
         */
        "href": string;
        /**
          * Toggle trailing icon visibility. - false (default): no icon - true or empty attribute (e.g., `<lbj-link icon>`): show default icon based on theme
          * @default false
         */
        "icon": boolean;
        /**
          * Optional override for the trailing icon when `icon` is true. Provide a value from `IconName` (e.g., `arrow-right`). Note: Does not by itself make the icon visible; `icon` must be true.
         */
        "iconName"?: IconName;
        /**
          * Display mode when nested inside another component.
         */
        "mode": string;
        /**
          * Link state active|inactive|undefined.
          * @default undefined
         */
        "state": LinkState;
        /**
          * The link style to display.
          * @default 'link'
         */
        "variant": LinkVariant;
    }
    /**
     * The simple search block.
     * @element lbj-simple-search
     */
    interface LbjSimpleSearch {
        /**
          * A string to force a two or three column.
         */
        "columns": string;
        /**
          * Facet column to filter.
         */
        "facetcol": string;
        /**
          * Facet value to filter.
         */
        "facetval": string;
        /**
          * The column name to filter.
         */
        "filtercol": string;
        /**
          * The value to filter.
         */
        "filtercolval": string;
        /**
          * Text to search.
         */
        "fulltext": string;
        /**
          * The headline for the search results.
         */
        "headline": string;
        /**
          * Load the results from the solr endpoint.
         */
        "loadResults": () => Promise<void>;
        /**
          * The number of results to return.
         */
        "max": string;
        /**
          * The number of results to skip.
         */
        "offset": number;
        /**
          * The URI to the solr index powered by JSON:API.
         */
        "solrindex": string;
        /**
          * A string to tack on the end for sorting.
         */
        "sort": string;
    }
    /**
     * The page title.
     * @element lbj-title
     */
    interface LbjTitle {
        /**
          * Optionally, add an accent line to highlight content.
          * @default false
         */
        "accent": boolean;
        /**
          * The HTML element to use.
          * @default 'div'
         */
        "element": string;
        /**
          * @default false
         */
        "hasHtml": boolean;
        /**
          * Optionally, preface the title with an SVG icon.
         */
        "icon": IconName;
        /**
          * Display mode when nested inside another component.
         */
        "mode": string;
        /**
          * Optionally, add a stripe on the bottom.
          * @default undefined
         */
        "stripe_color": StripeColor;
        /**
          * The text style to use.
          * @default 'paragraph'
         */
        "variant": TitleVariant;
        /**
          * Optionally, add a vertical stripe to the left of the title.
          * @default undefined
         */
        "vertical_stripe": VerticalStripeColor;
    }
}
declare global {
    /**
     * The primary button component.
     * @element lbj-button
     */
    interface HTMLLbjButtonElement extends Components.LbjButton, HTMLStencilElement {
    }
    var HTMLLbjButtonElement: {
        prototype: HTMLLbjButtonElement;
        new (): HTMLLbjButtonElement;
    };
    /**
     * Design icons for lyndon.
     * @element lbj-icon
     */
    interface HTMLLbjIconElement extends Components.LbjIcon, HTMLStencilElement {
    }
    var HTMLLbjIconElement: {
        prototype: HTMLLbjIconElement;
        new (): HTMLLbjIconElement;
    };
    /**
     * A introductory lede component.
     * @element lbj-lede
     */
    interface HTMLLbjLedeElement extends Components.LbjLede, HTMLStencilElement {
    }
    var HTMLLbjLedeElement: {
        prototype: HTMLLbjLedeElement;
        new (): HTMLLbjLedeElement;
    };
    /**
     * The primary link component.
     * @element lbj-link
     */
    interface HTMLLbjLinkElement extends Components.LbjLink, HTMLStencilElement {
    }
    var HTMLLbjLinkElement: {
        prototype: HTMLLbjLinkElement;
        new (): HTMLLbjLinkElement;
    };
    /**
     * The simple search block.
     * @element lbj-simple-search
     */
    interface HTMLLbjSimpleSearchElement extends Components.LbjSimpleSearch, HTMLStencilElement {
    }
    var HTMLLbjSimpleSearchElement: {
        prototype: HTMLLbjSimpleSearchElement;
        new (): HTMLLbjSimpleSearchElement;
    };
    /**
     * The page title.
     * @element lbj-title
     */
    interface HTMLLbjTitleElement extends Components.LbjTitle, HTMLStencilElement {
    }
    var HTMLLbjTitleElement: {
        prototype: HTMLLbjTitleElement;
        new (): HTMLLbjTitleElement;
    };
    interface HTMLElementTagNameMap {
        "lbj-button": HTMLLbjButtonElement;
        "lbj-icon": HTMLLbjIconElement;
        "lbj-lede": HTMLLbjLedeElement;
        "lbj-link": HTMLLbjLinkElement;
        "lbj-simple-search": HTMLLbjSimpleSearchElement;
        "lbj-title": HTMLLbjTitleElement;
    }
}
declare namespace LocalJSX {
    /**
     * The primary button component.
     * @element lbj-button
     */
    interface LbjButton {
        /**
          * Defines active state of button
         */
        "activeState"?: boolean;
        /**
          * The button case ( optional ) by default is Uppercase
          * @default 'uppercase'
         */
        "case"?: 'none' | 'capitalize' | 'uppercase' | 'lowercase';
        /**
          * Width of button
         */
        "fullwidth"?: boolean;
        /**
          * If no url, then falls back to <button> element (optional).
         */
        "href"?: string;
        /**
          * An icon to display to the right of text (optional).
         */
        "icon"?: IconName | undefined;
        /**
          * An icon to display to the left of text (optional).
         */
        "iconleft"?: IconName | undefined;
        /**
          * An icon to display to the right of text (optional).
          * @default Size.FULL
         */
        "iconsize"?: Size;
        /**
          * Determines if the button is a breakout button.
          * @default false
         */
        "isBreakout"?: boolean;
        /**
          * Display mode when nested inside another component.
         */
        "mode"?: string;
        /**
          * Modifier class
         */
        "modifier"?: string;
        /**
          * Dropdown nav items.
          * @default []
         */
        "navItems"?: { title: string; url: string }[];
        /**
          * The internal padding size. sm|md|lg|xl|xxl
          * @default Size.MD
         */
        "size"?: Size;
        /**
          * Defines target for links (optional).
         */
        "target"?: string;
        /**
          * Defines title case of button
         */
        "titleCase"?: boolean;
        /**
          * The button styling to display.
          * @default ButtonVariants.BTN_PRIMARY
         */
        "variant"?: ButtonVariant;
    }
    /**
     * Design icons for lyndon.
     * @element lbj-icon
     */
    interface LbjIcon {
        /**
          * The icon color to display.
          * @default IconColor.CURRENT
         */
        "color"?: IconColor;
        "filetype"?: string;
        /**
          * The registered icon to display.
          * @default IconName.ARROW_RIGHT
         */
        "name"?: IconName;
        /**
          * An optional property to add height/width to an icon.
         */
        "size"?: Size;
        /**
          * The icon variant to display.
          * @default 'default'
         */
        "variant"?: IconVariant;
    }
    /**
     * A introductory lede component.
     * @element lbj-lede
     */
    interface LbjLede {
        /**
          * The text contents of the accent title.
         */
        "accent"?: string;
        /**
          * The Array contents of the Author.
          * @default []
         */
        "author"?: Array<{ name: string; url: string }>;
        /**
          * @default false
         */
        "blank_target"?: boolean;
        /**
          * The different variants of the Lede.
          * @default 'lede'
         */
        "componentvariant"?: string;
        /**
          * The text contents of the date.
         */
        "date"?: string;
        /**
          * The text contents of the eyebrow title and url.
         */
        "eyebrow"?: Array<{ name: string; url: string }> | string | null;
        /**
          * The file type indicator.
         */
        "filetype"?: string;
        /**
          * Evaluate if Author slot has content.
         */
        "hasAuthor"?: boolean;
        /**
          * Evaluate if summary slot has content.
         */
        "hasSummary"?: boolean;
        /**
          * Evaluate if Topic slot has content.
         */
        "hasTopic"?: boolean;
        /**
          * The text contents of the headline title.
         */
        "headline"?: string;
        /**
          * @default false
         */
        "headline_html"?: boolean;
        /**
          * A wrapping URL for the headline title.
         */
        "href"?: string;
        "icon"?: string;
        /**
          * The text contents of the summary.
         */
        "summary"?: string;
        /**
          * The tags to display below the headline.
          * @default []
         */
        "tags"?: Array<{ name: string; url: string }>;
        /**
          * The array contents of the primary topic/ second eyebrow.
          * @default []
         */
        "topic"?: Array<{ name: string; url: string }>;
    }
    /**
     * The primary link component.
     * @element lbj-link
     */
    interface LbjLink {
        /**
          * Dropdown position.
          * @default 'floating'
         */
        "dropdown"?: 'static' | 'floating';
        /**
          * Whether the link has children.
         */
        "hasChildren"?: boolean;
        /**
          * The URL that the hyperlink points to.
         */
        "href"?: string;
        /**
          * Toggle trailing icon visibility. - false (default): no icon - true or empty attribute (e.g., `<lbj-link icon>`): show default icon based on theme
          * @default false
         */
        "icon"?: boolean;
        /**
          * Optional override for the trailing icon when `icon` is true. Provide a value from `IconName` (e.g., `arrow-right`). Note: Does not by itself make the icon visible; `icon` must be true.
         */
        "iconName"?: IconName;
        /**
          * Display mode when nested inside another component.
         */
        "mode"?: string;
        /**
          * Link state active|inactive|undefined.
          * @default undefined
         */
        "state"?: LinkState;
        /**
          * The link style to display.
          * @default 'link'
         */
        "variant"?: LinkVariant;
    }
    /**
     * The simple search block.
     * @element lbj-simple-search
     */
    interface LbjSimpleSearch {
        /**
          * A string to force a two or three column.
         */
        "columns"?: string;
        /**
          * Facet column to filter.
         */
        "facetcol"?: string;
        /**
          * Facet value to filter.
         */
        "facetval"?: string;
        /**
          * The column name to filter.
         */
        "filtercol"?: string;
        /**
          * The value to filter.
         */
        "filtercolval"?: string;
        /**
          * Text to search.
         */
        "fulltext"?: string;
        /**
          * The headline for the search results.
         */
        "headline"?: string;
        /**
          * The number of results to return.
         */
        "max"?: string;
        /**
          * The number of results to skip.
         */
        "offset"?: number;
        /**
          * The URI to the solr index powered by JSON:API.
         */
        "solrindex"?: string;
        /**
          * A string to tack on the end for sorting.
         */
        "sort"?: string;
    }
    /**
     * The page title.
     * @element lbj-title
     */
    interface LbjTitle {
        /**
          * Optionally, add an accent line to highlight content.
          * @default false
         */
        "accent"?: boolean;
        /**
          * The HTML element to use.
          * @default 'div'
         */
        "element"?: string;
        /**
          * @default false
         */
        "hasHtml"?: boolean;
        /**
          * Optionally, preface the title with an SVG icon.
         */
        "icon"?: IconName;
        /**
          * Display mode when nested inside another component.
         */
        "mode"?: string;
        /**
          * Optionally, add a stripe on the bottom.
          * @default undefined
         */
        "stripe_color"?: StripeColor;
        /**
          * The text style to use.
          * @default 'paragraph'
         */
        "variant"?: TitleVariant;
        /**
          * Optionally, add a vertical stripe to the left of the title.
          * @default undefined
         */
        "vertical_stripe"?: VerticalStripeColor;
    }
    interface IntrinsicElements {
        "lbj-button": LbjButton;
        "lbj-icon": LbjIcon;
        "lbj-lede": LbjLede;
        "lbj-link": LbjLink;
        "lbj-simple-search": LbjSimpleSearch;
        "lbj-title": LbjTitle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * The primary button component.
             * @element lbj-button
             */
            "lbj-button": LocalJSX.LbjButton & JSXBase.HTMLAttributes<HTMLLbjButtonElement>;
            /**
             * Design icons for lyndon.
             * @element lbj-icon
             */
            "lbj-icon": LocalJSX.LbjIcon & JSXBase.HTMLAttributes<HTMLLbjIconElement>;
            /**
             * A introductory lede component.
             * @element lbj-lede
             */
            "lbj-lede": LocalJSX.LbjLede & JSXBase.HTMLAttributes<HTMLLbjLedeElement>;
            /**
             * The primary link component.
             * @element lbj-link
             */
            "lbj-link": LocalJSX.LbjLink & JSXBase.HTMLAttributes<HTMLLbjLinkElement>;
            /**
             * The simple search block.
             * @element lbj-simple-search
             */
            "lbj-simple-search": LocalJSX.LbjSimpleSearch & JSXBase.HTMLAttributes<HTMLLbjSimpleSearchElement>;
            /**
             * The page title.
             * @element lbj-title
             */
            "lbj-title": LocalJSX.LbjTitle & JSXBase.HTMLAttributes<HTMLLbjTitleElement>;
        }
    }
}
