export const linkVariants = [
  'link',
  'content',
  'nav-primary-light',
  'nav-primary-dark',
  'nav-primary-bumblebee',
  'nav-secondary-dark',
  'nav-secondary-bumblebee',
  'nav-secondary-dual-color',
  'nav-footer',
  'nav-footer--alt',
  'nav-footer--modern',
  'nav-footer--modern-small',
  'nav-footer--alt-normal',
  'nav-footer--small',
  'nav-utility-primary',
  'nav-utility-primary-small',
  'nav-utility-secondary',
  'sub-nav',
  'sub-nav-secondary',
  'pagination',
  'tag',
  'tag-large',
  'task',
  'heading-1',
  'heading-2',
  'heading-3',
  'heading-4',
  'heading-5',
  'heading-6',
  'hero',
  'side-heading-link',
  'app-header-link',
  'eyebrow',
  'eyebrow-with-background',
  'small',
  'small-primary',
  'double-arrow',
  'arrow',
  'source-heading-link',
] as const;

export type LinkVariant = (typeof linkVariants)[number];

export type LinkState = 'active' | 'inactive' | 'active-menu';
