/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonVariant } from "./components/lbj-button/lbj-button-types";
import { IconColor, IconName, Size, TextStyles, VerticalStripeColor } from "./utils/enums";
import { CardVariant, DatePosition } from "./components/lbj-card/lbj-card-types";
import { StripeColor, TitleVariant } from "./components/lbj-title/lbj-title-types";
import { CollapseVariant } from "./components/lbj-collapse/lbj-collapse-types";
import { IconVariant } from "./components/lbj-icon/lbj-icon-types";
import { LinkState, LinkVariant } from "./components/lbj-link/lbj-link-types";
export { ButtonVariant } from "./components/lbj-button/lbj-button-types";
export { IconColor, IconName, Size, TextStyles, VerticalStripeColor } from "./utils/enums";
export { CardVariant, DatePosition } from "./components/lbj-card/lbj-card-types";
export { StripeColor, TitleVariant } from "./components/lbj-title/lbj-title-types";
export { CollapseVariant } from "./components/lbj-collapse/lbj-collapse-types";
export { IconVariant } from "./components/lbj-icon/lbj-icon-types";
export { LinkState, LinkVariant } from "./components/lbj-link/lbj-link-types";
export namespace Components {
    /**
     * The primary button component.
     * @element lbj-button
     */
    interface LbjButton {
        /**
          * Defines active state of button
         */
        "activeState": boolean;
        /**
          * The button case ( optional ) by default is Uppercase
          * @default 'uppercase'
         */
        "case": 'none' | 'capitalize' | 'uppercase' | 'lowercase';
        /**
          * Width of button
         */
        "fullwidth": boolean;
        /**
          * If no url, then falls back to <button> element (optional).
         */
        "href": string;
        /**
          * An icon to display to the right of text (optional).
         */
        "icon": IconName | undefined;
        /**
          * An icon to display to the left of text (optional).
         */
        "iconleft": IconName | undefined;
        /**
          * An icon to display to the right of text (optional).
          * @default Size.FULL
         */
        "iconsize": Size;
        /**
          * Determines if the button is a breakout button.
          * @default false
         */
        "isBreakout": boolean;
        /**
          * Display mode when nested inside another component.
         */
        "mode": string;
        /**
          * Modifier class
         */
        "modifier": string;
        /**
          * Dropdown nav items.
          * @default []
         */
        "navItems": { title: string; url: string }[];
        /**
          * The internal padding size. sm|md|lg|xl|xxl
          * @default Size.MD
         */
        "size": Size;
        /**
          * Defines target for links (optional).
         */
        "target": string;
        /**
          * Defines title case of button
         */
        "titleCase": boolean;
        /**
          * The button styling to display.
          * @default ButtonVariants.BTN_PRIMARY
         */
        "variant": ButtonVariant;
    }
    /**
     * The page title.
     * @element lbj-card
     */
    interface LbjCard {
        /**
          * @default false
         */
        "blank_target": boolean;
        /**
          * The text of the date title to display.
         */
        "date": string;
        /**
          * Date position.
          * @default 'below'
         */
        "dateposition": DatePosition;
        /**
          * The text of the eyebrow title to display.
         */
        "eyebrow": string;
        /**
          * The text of the headline title to display.
         */
        "headline": string;
        /**
          * The text of the date title to display.
         */
        "headlineVariant": TitleVariant;
        /**
          * @default false
         */
        "headline_html": boolean;
        /**
          * Optionally wrap the headline title with a URL.
         */
        "href": string;
        /**
          * Optionally, preface the headline with an SVG icon.
         */
        "icon": IconName;
        /**
          * Whether the card is a full size or grid display.
          * @default 'grid'
         */
        "variant": CardVariant;
    }
    /**
     * The primary collapse component.
     * @element lbj-collapse
     */
    interface LbjCollapse {
        /**
          * Optionally provide the details element's id for aria-controls.
          * @default `collapse-item-${Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15)}`
         */
        "detailsId": string;
        /**
          * Evaluate if headline slot has content.
         */
        "hasHeadline": boolean;
        /**
          * Evaluate if summary slot has content.
         */
        "hasSummary": boolean;
        /**
          * Evaluate if it's the first content.
         */
        "isOpen": boolean;
        /**
          * Sets the depth of the element for handling nested elements.  Works with variants ['collapsible-link'].
         */
        "level"?: number;
        /**
          * Additional classes to apply to the collapse.
         */
        "modifier": string;
        /**
          * Optionally provide a custom id for the event trigger.
         */
        "triggerId"?: string;
        /**
          * The collapse styling to display.
          * @default 'default'
         */
        "variant": CollapseVariant;
    }
    /**
     * Design icons for lyndon.
     * @element lbj-icon
     */
    interface LbjIcon {
        /**
          * The icon color to display.
          * @default IconColor.CURRENT
         */
        "color": IconColor;
        "filetype": string;
        /**
          * The registered icon to display.
          * @default IconName.ARROW_RIGHT
         */
        "name": IconName;
        /**
          * An optional property to add height/width to an icon.
         */
        "size": Size;
        /**
          * The icon variant to display.
          * @default 'default'
         */
        "variant": IconVariant;
    }
    /**
     * A introductory lede component.
     * @element lbj-lede
     */
    interface LbjLede {
        /**
          * The text contents of the accent title.
         */
        "accent": string;
        /**
          * The Array contents of the Author.
          * @default []
         */
        "author": Array<{ name: string; url: string }>;
        /**
          * @default false
         */
        "blank_target": boolean;
        /**
          * The different variants of the Lede.
          * @default 'lede'
         */
        "componentvariant": string;
        /**
          * The text contents of the date.
         */
        "date": string;
        /**
          * The text contents of the eyebrow title and url.
         */
        "eyebrow"?: Array<{ name: string; url: string }> | string | null;
        /**
          * The file type indicator.
         */
        "filetype": string;
        /**
          * Evaluate if Author slot has content.
         */
        "hasAuthor": boolean;
        /**
          * Evaluate if summary slot has content.
         */
        "hasSummary": boolean;
        /**
          * Evaluate if Topic slot has content.
         */
        "hasTopic": boolean;
        /**
          * The text contents of the headline title.
         */
        "headline": string;
        /**
          * @default false
         */
        "headline_html": boolean;
        /**
          * A wrapping URL for the headline title.
         */
        "href": string;
        "icon": string;
        /**
          * The text contents of the summary.
         */
        "summary": string;
        /**
          * The tags to display below the headline.
          * @default []
         */
        "tags": Array<{ name: string; url: string }>;
        /**
          * The array contents of the primary topic/ second eyebrow.
          * @default []
         */
        "topic": Array<{ name: string; url: string }>;
    }
    /**
     * The primary link component.
     * @element lbj-link
     */
    interface LbjLink {
        /**
          * Dropdown position.
          * @default 'floating'
         */
        "dropdown"?: 'static' | 'floating';
        /**
          * Whether the link has children.
         */
        "hasChildren": boolean;
        /**
          * The URL that the hyperlink points to.
         */
        "href": string;
        /**
          * Toggle trailing icon visibility. - false (default): no icon - true or empty attribute (e.g., `<lbj-link icon>`): show default icon based on theme
          * @default false
         */
        "icon": boolean;
        /**
          * Optional override for the trailing icon when `icon` is true. Provide a value from `IconName` (e.g., `arrow-right`). Note: Does not by itself make the icon visible; `icon` must be true.
         */
        "iconName"?: IconName;
        /**
          * Display mode when nested inside another component.
         */
        "mode": string;
        /**
          * Link state active|inactive|undefined.
          * @default undefined
         */
        "state": LinkState;
        /**
          * The link style to display.
          * @default 'link'
         */
        "variant": LinkVariant;
    }
    /**
     * The mini catalog block.
     * @element lbj-mini-catalog
     */
    interface LbjMiniCatalog {
        /**
          * @default true
         */
        "blank_target": boolean;
        /**
          * Control Properties
          * @default 3
         */
        "columns": number;
        /**
          * Data Property.
         */
        "csv": string;
        "csv_explainer": string;
        /**
          * @default 'drupalSettings'
         */
        "csv_global_var": string;
        /**
          * @default false
         */
        "description_below_title": boolean;
        /**
          * @default 'description'
         */
        "description_columns": string;
        /**
          * @default 'Summary'
         */
        "description_columns_label": string;
        /**
          * @default true
         */
        "description_columns_prefix_title": boolean;
        /**
          * @default true
         */
        "description_columns_prefix_title_skip_first": boolean;
        /**
          * @default '<br />'
         */
        "description_columns_separator": string;
        /**
          * @default ': '
         */
        "description_columns_suffix_separator": string;
        /**
          * @default false
         */
        "description_toggle_automatic_mini_tags_table": boolean;
        /**
          * @default 'tags;type;authors'
         */
        "explainer_columns": string;
        /**
          * @default 'Learn More About'
         */
        "explainer_cta": string;
        /**
          * @default 'type;eyebrow'
         */
        "eyebrow_key": string;
        /**
          * @default 'Filter by'
         */
        "facet_prepend": string;
        /**
          * @default 'Filter'
         */
        "filter_label": string;
        /**
          * @default ''
         */
        "filter_types": string;
        /**
          * @default false
         */
        "fulltext_hide": boolean;
        /**
          * @default true
         */
        "fulltext_highlight": boolean;
        /**
          * @default 'title;description;authors'
         */
        "fulltext_include": string;
        /**
          * @default 0.4
         */
        "fulltext_threshold": number;
        /**
          * Text Properties.
         */
        "headline": string;
        /**
          * @default TextStyles.HEADING2
         */
        "headline_variation": TextStyles;
        /**
          * @default false
         */
        "image_above_title": boolean;
        /**
          * @default ';'
         */
        "image_alt_separator": string;
        /**
          * @default true
         */
        "image_alt_support": boolean;
        /**
          * @default 'image'
         */
        "image_columns": string;
        /**
          * @default ''
         */
        "image_columns_label": string;
        /**
          * @default 'url'
         */
        "image_url_columns": string;
        /**
          * @default false
         */
        "image_with_title": boolean;
        /**
          * @default 'eyebrow;type;image'
         */
        "mini_tags_exclude": string;
        /**
          * @default true
         */
        "mini_tags_explainers": boolean;
        /**
          * @default true
         */
        "mini_tags_show": boolean;
        /**
          * @default 'authors;tags'
         */
        "multi_facet_tags_or": string;
        /**
          * @default 'Next'
         */
        "next_button": string;
        /**
          * @default IconName.CHEVRON_RIGHT
         */
        "next_icon": IconName;
        /**
          * @default 'No results found. Try expanding your search.'
         */
        "no_results": string;
        /**
          * @default 'title;url;description;eyebrow;date;image'
         */
        "not_facet": string;
        /**
          * @default 6
         */
        "pagination": number;
        /**
          * @default ButtonVariants.BTN_SECONDARY_NO_BORDER
         */
        "pagination_btn_variant": ButtonVariant;
        /**
          * @default 'of'
         */
        "pagination_separator": string;
        /**
          * @default 'initials'
         */
        "person_initials": string;
        /**
          * @default 'Previous'
         */
        "prev_button": string;
        /**
          * @default IconName.CHEVRON_LEFT
         */
        "prev_icon": IconName;
        /**
          * @default 'lede'
         */
        "rendering_mode_current": string;
        /**
          * @default 'lede'
         */
        "rendering_mode_set": string;
        /**
          * @default 'Clear filters'
         */
        "reset_button": string;
        /**
          * @default 'results found'
         */
        "results_count": string;
        /**
          * @default 'Search'
         */
        "search_button": string;
        /**
          * @default false
         */
        "show_description": boolean;
        /**
          * @default 'left;left;left'
         */
        "table_columns_alignments": string;
        /**
          * @default 'title;description;tags;authors'
         */
        "table_columns_includes": string;
        /**
          * @default 'top;top;top;top'
         */
        "table_columns_vertical_alignments": string;
        /**
          * @default '30;30;20;20'
         */
        "table_columns_widths": string;
        /**
          * @default 'title'
         */
        "title_columns": string;
        /**
          * @default 'Title'
         */
        "title_columns_label": string;
        /**
          * @default '&nbsp;'
         */
        "title_columns_separator": string;
        "toggle_csv_local": false;
        /**
          * @default true
         */
        "toggle_filter": boolean;
        /**
          * @default false
         */
        "toggle_multi_facets": boolean;
        /**
          * @default true
         */
        "toggle_rendering": boolean;
        /**
          * @default false
         */
        "toggle_top_pagination": boolean;
    }
    interface LbjPersonCard {
        /**
          * @default false
         */
        "blank_target": boolean;
        /**
          * The Link to person's Bluesky link.
          * @default undefined
         */
        "bluesky": string | null;
        /**
          * The text contents of the Company name.
         */
        "company": string;
        /**
          * Evaluate if Position slot has content.
         */
        "hasPosition": boolean;
        /**
          * @default false
         */
        "headline_html": boolean;
        /**
          * The link to person's linkedin link.
         */
        "linkedin": string;
        /**
          * The text contents of the Name of the Author.
         */
        "name": string;
        /**
          * The text contents of the Job title.
         */
        "position": string;
        /**
          * The Link to person's Threads link.
          * @default undefined
         */
        "threads": string | null;
        /**
          * The Link to person's Twitter link.
          * @default undefined
         */
        "twitter": string | null;
        /**
          * The Link to Author's profile page.
          * @default undefined
         */
        "url": string | null;
    }
    interface LbjPopover {
        "btn_icon": IconName;
        "btn_iconleft": IconName;
        "btn_iconsize": Size;
        "btn_size": Size;
        /**
          * @default ButtonVariants.BTN_PRIMARY
         */
        "btn_variant": ButtonVariant;
        /**
          * @default 'Trigger'
         */
        "popover_action_text": string;
        /**
          * @default Size.MD
         */
        "popover_close_iconsize": Size;
        /**
          * Controls where the popover dialog is rendered. 'local'  – inside Shadow DOM (default, existing behaviour). 'global' – portalled into document.body so the backdrop covers the full viewport.
          * @default 'local'
         */
        "renderMode": 'local' | 'global';
        /**
          * @default 'button'
         */
        "variant": string;
    }
    /**
     * The simple search block.
     * @element lbj-simple-search
     */
    interface LbjSimpleSearch {
        /**
          * A string to force a two or three column.
         */
        "columns": string;
        /**
          * Facet column to filter.
         */
        "facetcol": string;
        /**
          * Facet value to filter.
         */
        "facetval": string;
        /**
          * The column name to filter.
         */
        "filtercol": string;
        /**
          * The value to filter.
         */
        "filtercolval": string;
        /**
          * Text to search.
         */
        "fulltext": string;
        /**
          * The headline for the search results.
         */
        "headline": string;
        /**
          * Load the results from the solr endpoint.
         */
        "loadResults": () => Promise<void>;
        /**
          * The number of results to return.
         */
        "max": string;
        /**
          * The number of results to skip.
         */
        "offset": number;
        /**
          * The URI to the solr index powered by JSON:API.
         */
        "solrindex": string;
        /**
          * A string to tack on the end for sorting.
         */
        "sort": string;
    }
    /**
     * The page title.
     * @element lbj-title
     */
    interface LbjTitle {
        /**
          * Optionally, add an accent line to highlight content.
          * @default false
         */
        "accent": boolean;
        /**
          * The HTML element to use.
          * @default 'div'
         */
        "element": string;
        /**
          * @default false
         */
        "hasHtml": boolean;
        /**
          * Optionally, preface the title with an SVG icon.
         */
        "icon": IconName;
        /**
          * Display mode when nested inside another component.
         */
        "mode": string;
        /**
          * Optionally, add a stripe on the bottom.
          * @default undefined
         */
        "stripe_color": StripeColor;
        /**
          * The text style to use.
          * @default 'paragraph'
         */
        "variant": TitleVariant;
        /**
          * Optionally, add a vertical stripe to the left of the title.
          * @default undefined
         */
        "vertical_stripe": VerticalStripeColor;
    }
}
export interface LbjCollapseCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLbjCollapseElement;
}
declare global {
    /**
     * The primary button component.
     * @element lbj-button
     */
    interface HTMLLbjButtonElement extends Components.LbjButton, HTMLStencilElement {
    }
    var HTMLLbjButtonElement: {
        prototype: HTMLLbjButtonElement;
        new (): HTMLLbjButtonElement;
    };
    /**
     * The page title.
     * @element lbj-card
     */
    interface HTMLLbjCardElement extends Components.LbjCard, HTMLStencilElement {
    }
    var HTMLLbjCardElement: {
        prototype: HTMLLbjCardElement;
        new (): HTMLLbjCardElement;
    };
    interface HTMLLbjCollapseElementEventMap {
        "stateChanged": { state: boolean; id: string };
    }
    /**
     * The primary collapse component.
     * @element lbj-collapse
     */
    interface HTMLLbjCollapseElement extends Components.LbjCollapse, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLbjCollapseElementEventMap>(type: K, listener: (this: HTMLLbjCollapseElement, ev: LbjCollapseCustomEvent<HTMLLbjCollapseElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLbjCollapseElementEventMap>(type: K, listener: (this: HTMLLbjCollapseElement, ev: LbjCollapseCustomEvent<HTMLLbjCollapseElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLbjCollapseElement: {
        prototype: HTMLLbjCollapseElement;
        new (): HTMLLbjCollapseElement;
    };
    /**
     * Design icons for lyndon.
     * @element lbj-icon
     */
    interface HTMLLbjIconElement extends Components.LbjIcon, HTMLStencilElement {
    }
    var HTMLLbjIconElement: {
        prototype: HTMLLbjIconElement;
        new (): HTMLLbjIconElement;
    };
    /**
     * A introductory lede component.
     * @element lbj-lede
     */
    interface HTMLLbjLedeElement extends Components.LbjLede, HTMLStencilElement {
    }
    var HTMLLbjLedeElement: {
        prototype: HTMLLbjLedeElement;
        new (): HTMLLbjLedeElement;
    };
    /**
     * The primary link component.
     * @element lbj-link
     */
    interface HTMLLbjLinkElement extends Components.LbjLink, HTMLStencilElement {
    }
    var HTMLLbjLinkElement: {
        prototype: HTMLLbjLinkElement;
        new (): HTMLLbjLinkElement;
    };
    /**
     * The mini catalog block.
     * @element lbj-mini-catalog
     */
    interface HTMLLbjMiniCatalogElement extends Components.LbjMiniCatalog, HTMLStencilElement {
    }
    var HTMLLbjMiniCatalogElement: {
        prototype: HTMLLbjMiniCatalogElement;
        new (): HTMLLbjMiniCatalogElement;
    };
    interface HTMLLbjPersonCardElement extends Components.LbjPersonCard, HTMLStencilElement {
    }
    var HTMLLbjPersonCardElement: {
        prototype: HTMLLbjPersonCardElement;
        new (): HTMLLbjPersonCardElement;
    };
    interface HTMLLbjPopoverElement extends Components.LbjPopover, HTMLStencilElement {
    }
    var HTMLLbjPopoverElement: {
        prototype: HTMLLbjPopoverElement;
        new (): HTMLLbjPopoverElement;
    };
    /**
     * The simple search block.
     * @element lbj-simple-search
     */
    interface HTMLLbjSimpleSearchElement extends Components.LbjSimpleSearch, HTMLStencilElement {
    }
    var HTMLLbjSimpleSearchElement: {
        prototype: HTMLLbjSimpleSearchElement;
        new (): HTMLLbjSimpleSearchElement;
    };
    /**
     * The page title.
     * @element lbj-title
     */
    interface HTMLLbjTitleElement extends Components.LbjTitle, HTMLStencilElement {
    }
    var HTMLLbjTitleElement: {
        prototype: HTMLLbjTitleElement;
        new (): HTMLLbjTitleElement;
    };
    interface HTMLElementTagNameMap {
        "lbj-button": HTMLLbjButtonElement;
        "lbj-card": HTMLLbjCardElement;
        "lbj-collapse": HTMLLbjCollapseElement;
        "lbj-icon": HTMLLbjIconElement;
        "lbj-lede": HTMLLbjLedeElement;
        "lbj-link": HTMLLbjLinkElement;
        "lbj-mini-catalog": HTMLLbjMiniCatalogElement;
        "lbj-person-card": HTMLLbjPersonCardElement;
        "lbj-popover": HTMLLbjPopoverElement;
        "lbj-simple-search": HTMLLbjSimpleSearchElement;
        "lbj-title": HTMLLbjTitleElement;
    }
}
declare namespace LocalJSX {
    /**
     * The primary button component.
     * @element lbj-button
     */
    interface LbjButton {
        /**
          * Defines active state of button
         */
        "activeState"?: boolean;
        /**
          * The button case ( optional ) by default is Uppercase
          * @default 'uppercase'
         */
        "case"?: 'none' | 'capitalize' | 'uppercase' | 'lowercase';
        /**
          * Width of button
         */
        "fullwidth"?: boolean;
        /**
          * If no url, then falls back to <button> element (optional).
         */
        "href"?: string;
        /**
          * An icon to display to the right of text (optional).
         */
        "icon"?: IconName | undefined;
        /**
          * An icon to display to the left of text (optional).
         */
        "iconleft"?: IconName | undefined;
        /**
          * An icon to display to the right of text (optional).
          * @default Size.FULL
         */
        "iconsize"?: Size;
        /**
          * Determines if the button is a breakout button.
          * @default false
         */
        "isBreakout"?: boolean;
        /**
          * Display mode when nested inside another component.
         */
        "mode"?: string;
        /**
          * Modifier class
         */
        "modifier"?: string;
        /**
          * Dropdown nav items.
          * @default []
         */
        "navItems"?: { title: string; url: string }[];
        /**
          * The internal padding size. sm|md|lg|xl|xxl
          * @default Size.MD
         */
        "size"?: Size;
        /**
          * Defines target for links (optional).
         */
        "target"?: string;
        /**
          * Defines title case of button
         */
        "titleCase"?: boolean;
        /**
          * The button styling to display.
          * @default ButtonVariants.BTN_PRIMARY
         */
        "variant"?: ButtonVariant;
    }
    /**
     * The page title.
     * @element lbj-card
     */
    interface LbjCard {
        /**
          * @default false
         */
        "blank_target"?: boolean;
        /**
          * The text of the date title to display.
         */
        "date"?: string;
        /**
          * Date position.
          * @default 'below'
         */
        "dateposition"?: DatePosition;
        /**
          * The text of the eyebrow title to display.
         */
        "eyebrow"?: string;
        /**
          * The text of the headline title to display.
         */
        "headline"?: string;
        /**
          * The text of the date title to display.
         */
        "headlineVariant"?: TitleVariant;
        /**
          * @default false
         */
        "headline_html"?: boolean;
        /**
          * Optionally wrap the headline title with a URL.
         */
        "href"?: string;
        /**
          * Optionally, preface the headline with an SVG icon.
         */
        "icon"?: IconName;
        /**
          * Whether the card is a full size or grid display.
          * @default 'grid'
         */
        "variant"?: CardVariant;
    }
    /**
     * The primary collapse component.
     * @element lbj-collapse
     */
    interface LbjCollapse {
        /**
          * Optionally provide the details element's id for aria-controls.
          * @default `collapse-item-${Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15)}`
         */
        "detailsId"?: string;
        /**
          * Evaluate if headline slot has content.
         */
        "hasHeadline"?: boolean;
        /**
          * Evaluate if summary slot has content.
         */
        "hasSummary"?: boolean;
        /**
          * Evaluate if it's the first content.
         */
        "isOpen"?: boolean;
        /**
          * Sets the depth of the element for handling nested elements.  Works with variants ['collapsible-link'].
         */
        "level"?: number;
        /**
          * Additional classes to apply to the collapse.
         */
        "modifier"?: string;
        "onStateChanged"?: (event: LbjCollapseCustomEvent<{ state: boolean; id: string }>) => void;
        /**
          * Optionally provide a custom id for the event trigger.
         */
        "triggerId"?: string;
        /**
          * The collapse styling to display.
          * @default 'default'
         */
        "variant"?: CollapseVariant;
    }
    /**
     * Design icons for lyndon.
     * @element lbj-icon
     */
    interface LbjIcon {
        /**
          * The icon color to display.
          * @default IconColor.CURRENT
         */
        "color"?: IconColor;
        "filetype"?: string;
        /**
          * The registered icon to display.
          * @default IconName.ARROW_RIGHT
         */
        "name"?: IconName;
        /**
          * An optional property to add height/width to an icon.
         */
        "size"?: Size;
        /**
          * The icon variant to display.
          * @default 'default'
         */
        "variant"?: IconVariant;
    }
    /**
     * A introductory lede component.
     * @element lbj-lede
     */
    interface LbjLede {
        /**
          * The text contents of the accent title.
         */
        "accent"?: string;
        /**
          * The Array contents of the Author.
          * @default []
         */
        "author"?: Array<{ name: string; url: string }>;
        /**
          * @default false
         */
        "blank_target"?: boolean;
        /**
          * The different variants of the Lede.
          * @default 'lede'
         */
        "componentvariant"?: string;
        /**
          * The text contents of the date.
         */
        "date"?: string;
        /**
          * The text contents of the eyebrow title and url.
         */
        "eyebrow"?: Array<{ name: string; url: string }> | string | null;
        /**
          * The file type indicator.
         */
        "filetype"?: string;
        /**
          * Evaluate if Author slot has content.
         */
        "hasAuthor"?: boolean;
        /**
          * Evaluate if summary slot has content.
         */
        "hasSummary"?: boolean;
        /**
          * Evaluate if Topic slot has content.
         */
        "hasTopic"?: boolean;
        /**
          * The text contents of the headline title.
         */
        "headline"?: string;
        /**
          * @default false
         */
        "headline_html"?: boolean;
        /**
          * A wrapping URL for the headline title.
         */
        "href"?: string;
        "icon"?: string;
        /**
          * The text contents of the summary.
         */
        "summary"?: string;
        /**
          * The tags to display below the headline.
          * @default []
         */
        "tags"?: Array<{ name: string; url: string }>;
        /**
          * The array contents of the primary topic/ second eyebrow.
          * @default []
         */
        "topic"?: Array<{ name: string; url: string }>;
    }
    /**
     * The primary link component.
     * @element lbj-link
     */
    interface LbjLink {
        /**
          * Dropdown position.
          * @default 'floating'
         */
        "dropdown"?: 'static' | 'floating';
        /**
          * Whether the link has children.
         */
        "hasChildren"?: boolean;
        /**
          * The URL that the hyperlink points to.
         */
        "href"?: string;
        /**
          * Toggle trailing icon visibility. - false (default): no icon - true or empty attribute (e.g., `<lbj-link icon>`): show default icon based on theme
          * @default false
         */
        "icon"?: boolean;
        /**
          * Optional override for the trailing icon when `icon` is true. Provide a value from `IconName` (e.g., `arrow-right`). Note: Does not by itself make the icon visible; `icon` must be true.
         */
        "iconName"?: IconName;
        /**
          * Display mode when nested inside another component.
         */
        "mode"?: string;
        /**
          * Link state active|inactive|undefined.
          * @default undefined
         */
        "state"?: LinkState;
        /**
          * The link style to display.
          * @default 'link'
         */
        "variant"?: LinkVariant;
    }
    /**
     * The mini catalog block.
     * @element lbj-mini-catalog
     */
    interface LbjMiniCatalog {
        /**
          * @default true
         */
        "blank_target"?: boolean;
        /**
          * Control Properties
          * @default 3
         */
        "columns"?: number;
        /**
          * Data Property.
         */
        "csv"?: string;
        "csv_explainer"?: string;
        /**
          * @default 'drupalSettings'
         */
        "csv_global_var"?: string;
        /**
          * @default false
         */
        "description_below_title"?: boolean;
        /**
          * @default 'description'
         */
        "description_columns"?: string;
        /**
          * @default 'Summary'
         */
        "description_columns_label"?: string;
        /**
          * @default true
         */
        "description_columns_prefix_title"?: boolean;
        /**
          * @default true
         */
        "description_columns_prefix_title_skip_first"?: boolean;
        /**
          * @default '<br />'
         */
        "description_columns_separator"?: string;
        /**
          * @default ': '
         */
        "description_columns_suffix_separator"?: string;
        /**
          * @default false
         */
        "description_toggle_automatic_mini_tags_table"?: boolean;
        /**
          * @default 'tags;type;authors'
         */
        "explainer_columns"?: string;
        /**
          * @default 'Learn More About'
         */
        "explainer_cta"?: string;
        /**
          * @default 'type;eyebrow'
         */
        "eyebrow_key"?: string;
        /**
          * @default 'Filter by'
         */
        "facet_prepend"?: string;
        /**
          * @default 'Filter'
         */
        "filter_label"?: string;
        /**
          * @default ''
         */
        "filter_types"?: string;
        /**
          * @default false
         */
        "fulltext_hide"?: boolean;
        /**
          * @default true
         */
        "fulltext_highlight"?: boolean;
        /**
          * @default 'title;description;authors'
         */
        "fulltext_include"?: string;
        /**
          * @default 0.4
         */
        "fulltext_threshold"?: number;
        /**
          * Text Properties.
         */
        "headline"?: string;
        /**
          * @default TextStyles.HEADING2
         */
        "headline_variation"?: TextStyles;
        /**
          * @default false
         */
        "image_above_title"?: boolean;
        /**
          * @default ';'
         */
        "image_alt_separator"?: string;
        /**
          * @default true
         */
        "image_alt_support"?: boolean;
        /**
          * @default 'image'
         */
        "image_columns"?: string;
        /**
          * @default ''
         */
        "image_columns_label"?: string;
        /**
          * @default 'url'
         */
        "image_url_columns"?: string;
        /**
          * @default false
         */
        "image_with_title"?: boolean;
        /**
          * @default 'eyebrow;type;image'
         */
        "mini_tags_exclude"?: string;
        /**
          * @default true
         */
        "mini_tags_explainers"?: boolean;
        /**
          * @default true
         */
        "mini_tags_show"?: boolean;
        /**
          * @default 'authors;tags'
         */
        "multi_facet_tags_or"?: string;
        /**
          * @default 'Next'
         */
        "next_button"?: string;
        /**
          * @default IconName.CHEVRON_RIGHT
         */
        "next_icon"?: IconName;
        /**
          * @default 'No results found. Try expanding your search.'
         */
        "no_results"?: string;
        /**
          * @default 'title;url;description;eyebrow;date;image'
         */
        "not_facet"?: string;
        /**
          * @default 6
         */
        "pagination"?: number;
        /**
          * @default ButtonVariants.BTN_SECONDARY_NO_BORDER
         */
        "pagination_btn_variant"?: ButtonVariant;
        /**
          * @default 'of'
         */
        "pagination_separator"?: string;
        /**
          * @default 'initials'
         */
        "person_initials"?: string;
        /**
          * @default 'Previous'
         */
        "prev_button"?: string;
        /**
          * @default IconName.CHEVRON_LEFT
         */
        "prev_icon"?: IconName;
        /**
          * @default 'lede'
         */
        "rendering_mode_current"?: string;
        /**
          * @default 'lede'
         */
        "rendering_mode_set"?: string;
        /**
          * @default 'Clear filters'
         */
        "reset_button"?: string;
        /**
          * @default 'results found'
         */
        "results_count"?: string;
        /**
          * @default 'Search'
         */
        "search_button"?: string;
        /**
          * @default false
         */
        "show_description"?: boolean;
        /**
          * @default 'left;left;left'
         */
        "table_columns_alignments"?: string;
        /**
          * @default 'title;description;tags;authors'
         */
        "table_columns_includes"?: string;
        /**
          * @default 'top;top;top;top'
         */
        "table_columns_vertical_alignments"?: string;
        /**
          * @default '30;30;20;20'
         */
        "table_columns_widths"?: string;
        /**
          * @default 'title'
         */
        "title_columns"?: string;
        /**
          * @default 'Title'
         */
        "title_columns_label"?: string;
        /**
          * @default '&nbsp;'
         */
        "title_columns_separator"?: string;
        "toggle_csv_local"?: false;
        /**
          * @default true
         */
        "toggle_filter"?: boolean;
        /**
          * @default false
         */
        "toggle_multi_facets"?: boolean;
        /**
          * @default true
         */
        "toggle_rendering"?: boolean;
        /**
          * @default false
         */
        "toggle_top_pagination"?: boolean;
    }
    interface LbjPersonCard {
        /**
          * @default false
         */
        "blank_target"?: boolean;
        /**
          * The Link to person's Bluesky link.
          * @default undefined
         */
        "bluesky"?: string | null;
        /**
          * The text contents of the Company name.
         */
        "company"?: string;
        /**
          * Evaluate if Position slot has content.
         */
        "hasPosition"?: boolean;
        /**
          * @default false
         */
        "headline_html"?: boolean;
        /**
          * The link to person's linkedin link.
         */
        "linkedin"?: string;
        /**
          * The text contents of the Name of the Author.
         */
        "name"?: string;
        /**
          * The text contents of the Job title.
         */
        "position"?: string;
        /**
          * The Link to person's Threads link.
          * @default undefined
         */
        "threads"?: string | null;
        /**
          * The Link to person's Twitter link.
          * @default undefined
         */
        "twitter"?: string | null;
        /**
          * The Link to Author's profile page.
          * @default undefined
         */
        "url"?: string | null;
    }
    interface LbjPopover {
        "btn_icon"?: IconName;
        "btn_iconleft"?: IconName;
        "btn_iconsize"?: Size;
        "btn_size"?: Size;
        /**
          * @default ButtonVariants.BTN_PRIMARY
         */
        "btn_variant"?: ButtonVariant;
        /**
          * @default 'Trigger'
         */
        "popover_action_text"?: string;
        /**
          * @default Size.MD
         */
        "popover_close_iconsize"?: Size;
        /**
          * Controls where the popover dialog is rendered. 'local'  – inside Shadow DOM (default, existing behaviour). 'global' – portalled into document.body so the backdrop covers the full viewport.
          * @default 'local'
         */
        "renderMode"?: 'local' | 'global';
        /**
          * @default 'button'
         */
        "variant"?: string;
    }
    /**
     * The simple search block.
     * @element lbj-simple-search
     */
    interface LbjSimpleSearch {
        /**
          * A string to force a two or three column.
         */
        "columns"?: string;
        /**
          * Facet column to filter.
         */
        "facetcol"?: string;
        /**
          * Facet value to filter.
         */
        "facetval"?: string;
        /**
          * The column name to filter.
         */
        "filtercol"?: string;
        /**
          * The value to filter.
         */
        "filtercolval"?: string;
        /**
          * Text to search.
         */
        "fulltext"?: string;
        /**
          * The headline for the search results.
         */
        "headline"?: string;
        /**
          * The number of results to return.
         */
        "max"?: string;
        /**
          * The number of results to skip.
         */
        "offset"?: number;
        /**
          * The URI to the solr index powered by JSON:API.
         */
        "solrindex"?: string;
        /**
          * A string to tack on the end for sorting.
         */
        "sort"?: string;
    }
    /**
     * The page title.
     * @element lbj-title
     */
    interface LbjTitle {
        /**
          * Optionally, add an accent line to highlight content.
          * @default false
         */
        "accent"?: boolean;
        /**
          * The HTML element to use.
          * @default 'div'
         */
        "element"?: string;
        /**
          * @default false
         */
        "hasHtml"?: boolean;
        /**
          * Optionally, preface the title with an SVG icon.
         */
        "icon"?: IconName;
        /**
          * Display mode when nested inside another component.
         */
        "mode"?: string;
        /**
          * Optionally, add a stripe on the bottom.
          * @default undefined
         */
        "stripe_color"?: StripeColor;
        /**
          * The text style to use.
          * @default 'paragraph'
         */
        "variant"?: TitleVariant;
        /**
          * Optionally, add a vertical stripe to the left of the title.
          * @default undefined
         */
        "vertical_stripe"?: VerticalStripeColor;
    }
    interface IntrinsicElements {
        "lbj-button": LbjButton;
        "lbj-card": LbjCard;
        "lbj-collapse": LbjCollapse;
        "lbj-icon": LbjIcon;
        "lbj-lede": LbjLede;
        "lbj-link": LbjLink;
        "lbj-mini-catalog": LbjMiniCatalog;
        "lbj-person-card": LbjPersonCard;
        "lbj-popover": LbjPopover;
        "lbj-simple-search": LbjSimpleSearch;
        "lbj-title": LbjTitle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * The primary button component.
             * @element lbj-button
             */
            "lbj-button": LocalJSX.LbjButton & JSXBase.HTMLAttributes<HTMLLbjButtonElement>;
            /**
             * The page title.
             * @element lbj-card
             */
            "lbj-card": LocalJSX.LbjCard & JSXBase.HTMLAttributes<HTMLLbjCardElement>;
            /**
             * The primary collapse component.
             * @element lbj-collapse
             */
            "lbj-collapse": LocalJSX.LbjCollapse & JSXBase.HTMLAttributes<HTMLLbjCollapseElement>;
            /**
             * Design icons for lyndon.
             * @element lbj-icon
             */
            "lbj-icon": LocalJSX.LbjIcon & JSXBase.HTMLAttributes<HTMLLbjIconElement>;
            /**
             * A introductory lede component.
             * @element lbj-lede
             */
            "lbj-lede": LocalJSX.LbjLede & JSXBase.HTMLAttributes<HTMLLbjLedeElement>;
            /**
             * The primary link component.
             * @element lbj-link
             */
            "lbj-link": LocalJSX.LbjLink & JSXBase.HTMLAttributes<HTMLLbjLinkElement>;
            /**
             * The mini catalog block.
             * @element lbj-mini-catalog
             */
            "lbj-mini-catalog": LocalJSX.LbjMiniCatalog & JSXBase.HTMLAttributes<HTMLLbjMiniCatalogElement>;
            "lbj-person-card": LocalJSX.LbjPersonCard & JSXBase.HTMLAttributes<HTMLLbjPersonCardElement>;
            "lbj-popover": LocalJSX.LbjPopover & JSXBase.HTMLAttributes<HTMLLbjPopoverElement>;
            /**
             * The simple search block.
             * @element lbj-simple-search
             */
            "lbj-simple-search": LocalJSX.LbjSimpleSearch & JSXBase.HTMLAttributes<HTMLLbjSimpleSearchElement>;
            /**
             * The page title.
             * @element lbj-title
             */
            "lbj-title": LocalJSX.LbjTitle & JSXBase.HTMLAttributes<HTMLLbjTitleElement>;
        }
    }
}
